In [1]:
import numpy as np

In [14]:
# create 2d array using meshgrid
x = np.arange(0, 5)
y = x + 1

In [15]:
x, y

(array([0, 1, 2, 3, 4]), array([1, 2, 3, 4, 5]))

In [16]:
mesh = np.meshgrid(x, y)

In [21]:
mesh0 = mesh[0]
mesh1 = mesh[1]

In [20]:
mesh0.ravel()

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       2, 3, 4])

In [25]:
mesh1.ravel()

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5])