### Создание данных

Создадим массив 2d массив данных, который можно будет использовать. 

In [50]:
import pandas as pd
import numpy as np

sclaes = np.linspace(1, 50, 2)
means = np.linspace(1, 50, 1)

randoms  = np.array([np.random.normal(loc, scale, 10) for scale in sclaes for loc in means])
sclaes.shape, means.shape, sclaes, means
sclaes

array([ 1., 50.])

Посмотрим на созданный массив.

In [51]:
randoms

array([[ 2.52438206e+00,  2.02588989e+00,  1.88229969e+00,
         6.60416104e-01, -3.76434421e-01,  1.68992308e+00,
         7.83124721e-01, -5.84178865e-03,  1.37475466e+00,
         1.31588990e+00],
       [ 1.70877206e+01,  2.64950167e+01,  4.27012221e+01,
         2.33537307e+01,  5.60021680e+01, -1.39058660e+01,
         3.09679558e+01,  2.72436661e+01, -4.22414309e+01,
         9.90088097e+01]])

Посмотрим на статистики данных массивов


In [52]:
for i in randoms:
    print(np.mean(i), np.std(i)) 

1.1874403896222228 0.8711008754582108
26.671299264768066 35.870761917426954


Добавим массивы в DataFrame.

In [53]:
randoms.T
data = pd.DataFrame(randoms.T)
data

0          1
0  2.524382  17.087721
1  2.025890  26.495017
2  1.882300  42.701222
3  0.660416  23.353731
4 -0.376434  56.002168
5  1.689923 -13.905866
6  0.783125  30.967956
7 -0.005842  27.243666
8  1.374755 -42.241431
9  1.315890  99.008810

Создадим объект, который можно будет использовать для трансформации данных.

In [54]:
from sklearn.preprocessing import StandardScaler

scaller = StandardScaler()
scaller.fit(data)

StandardScaler()

Преобразуем данные

In [55]:
scalleddata = scaller.transform(data)

In [56]:
scalleddata

array([[ 1.53477251, -0.26716964],
       [ 0.96251711, -0.00491438],
       [ 0.79767949,  0.44687991],
       [-0.60500948, -0.09248671],
       [-1.79528555,  0.81768179],
       [ 0.5768364 , -1.13120444],
       [-0.46414334,  0.11978158],
       [-1.36985533,  0.01595636],
       [ 0.21503167, -1.92113929],
       [ 0.14745652,  2.01661483]])

Посмотрим на статистики, которые были получыены STandardScaler()

In [57]:
scaller.mean_, scaller.scale_

(array([ 1.18744039, 26.67129926]), array([ 0.87110088, 35.87076192]))

In [74]:
scaller.transform(data.iloc[:, 0:1])

ValueError: X has 1 features, but StandardScaler is expecting 2 features as input.